export * from "./listsActions";
export * from "./cardsActions";

export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  ADD_LIST: "ADD_LIST",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  INITIAL_VALUE: "INITIAL_VALUE",
  DELETE_CARD: "DELETE_CARD",
  DELETE_LIST:"DELETE_LIST",
  UPDATE_ONE_TASK: "UPDATE_ONE_TASK",
  RENAME_LIST: "RENAME_LIST",
  
};
